# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Deploy
on:
  workflow_run:
    workflows: ["Go"]
    types:
      - completed
jobs:
  wait_for_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Approval required
        uses: peter-evans/wait-for-approval@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          timeout-minutes: 1440 # Timeout after 24 hours
          reactivate: false

  deploy:
    runs-on: ubuntu-latest
    needs: wait_for_approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Deploy
        run: |
          # Add your deployment script here
          echo "Deploying application..."
